dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk8
  - openjdk8
  #- openjdk11
branches:
  only:
    - master
    - develop
before_script:
  # Undo _JAVA_OPTIONS environment variable
  - unset _JAVA_OPTIONS
script: "mvn verify"
after_success:
  - bash <(curl -s https://codecov.io/bash)
