dist: trusty
language: java
sudo: false
jdk:
  - openjdk8
  - oraclejdk8
branches:
  only:
    - master
    - develop
script: "mvn verify"
# Undo _JAVA_OPTIONS environment variable
before_script:
  - unset _JAVA_OPTIONS
after_success:
  - bash <(curl -s https://codecov.io/bash)
